### ISSUE TITLE
Empty strings are only removed from multi-value params

### ISSUE THREAD

**Issue by phebal** [projecthydra-labs/hydra-editor#75]
Cleaning params using `HydraEditor::Form#model_attributes` doesn't clean single-value params containing empty strings. This is related to https://github.com/projecthydra/sufia/issues/941

**Comment by jcoyne** [comment]
@phebal On single values, I want to persist empty strings.  Otherwise I can't clear out a value. This is most similar to how rails works with ActiveRecord.

**Comment by phebal** [comment]
@jcoyne you're right, I think that changed in Rails 4, I should have checked that. I'll close the corresponding PR, sorry about this.
